name: Check uv lockfile
on:
  workflow_call:
    inputs:
      working-directory:
        description: Directory where uv.lock is in. Leave blank for the root direcotry.
        default: "."
        required: false
        type: string

permissions:
  contents: read

jobs:
  check-lockfile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{inputs.working-directory}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(vars) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "latest"

      - name: Check lockfile
        run: uv lock --locked