name: Create Github Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }} # Required for gh commands

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  update-tags:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: main

      - name: Update README.md
        run: |
          sed -Ei 's/@v\S+/@${{ github.ref_name }}/g' readme.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: "Update workflows in readme.md to version ${{ github.ref_name }}"

      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
