name: Create Github Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }} # Required for gh commands

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml

  update-tags:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: main

      - name: Update README.md
        run: |
          sed -Ei 's/@v\S+/@${{ github.ref_name }}/g' readme.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "Update workflows in readme.md to version ${{ github.ref_name }}"

      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
