name: Lint and check uv lockfile (Python)
on:
  workflow_call:
    inputs:
      directory:
        description: Directory to run checks in.
        default: ${{ github.workspace }}
        required: false
        type: string
      check-standard-rules:
        description: |-
          Whether to also run Ruff against the ruff.toml in the common-actions repository.
          Defaults to true.
          Note: If a ruff.toml exists in the repository, it will always be checked, regardless of this setting.
        default: true
        required: false
        type: boolean
      check-uv-lockfile:
        description: Whether to check the uv lockfile.
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      - name: Format
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2
        with:
          args: "format --check"
          src: ${{ inputs.directory }}

      - name: Check if ruff.toml exists in repo
        id: ruff
        run: |
          echo "has_ruff=$( [[ -f ruff.toml ]] && echo true || echo false )" >> "$GITHUB_OUTPUT"

      - name: Lint (using ruff.toml from the project)
        if: fromJson(steps.ruff.outputs.has_ruff)
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2

      - name: Fetch ruff.toml from common-actions repo
        if: inputs.check-standard-rules
        uses: actions/checkout@v4
        with:
          repository: nuhs-projects/common-actions
          path: repo-name-${{ github.run_id }}-${{ github.run_number }}
          sparse-checkout: ruff.toml
          sparse-checkout-cone-mode: false

      # Workaround as actions/checkout doesn't let us clone outside of $GITHUB_WORKSPACE
      # https://github.com/actions/checkout/issues/197
      - run: mv ${{ github.workspace }}/repo-name-${{ github.run_id }}-${{ github.run_number }} /tmp
        if: inputs.check-standard-rules

      - name: Lint (using ruff.toml from common-actions)
        if: inputs.check-standard-rules
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2
        with:
          args: "--config /tmp/repo-name-${{ github.run_id }}-${{ github.run_number }}/ruff.toml check"
          src: ${{ inputs.directory }}

  check-lockfile:
    runs-on: ubuntu-latest
    if: inputs.check-uv-lockfile
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "latest"

      - name: Check lockfile
        run: uv lock --locked
