name: Create Github Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }} # Required for gh commands

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  update-tags:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
